#!/bin/bash

#SBATCH -J LMM_trainings
#SBATCH -o logs/vit-l-16_all_pretraining.out                       # STDOUT (%j = JobId)
#SBATCH -e logs/vit-l-16_all_pretraining.err                       # STDERR (%j = JobId)
#SBATCH -N 1
#SBATCH -n 1
#SBATCH --mem=64G
#SBATCH -t 72:00:00

#SBATCH -M edge
#SBATCH -p edge-gpu
#SBATCH -G 1

##SBATCH -A mpurohit                                      # Account hours will be pulled from (commented out with double # in front)
#SBATCH --mail-type=ALL                                   # Send a notification when the job starts, stops, or fails
#SBATCH --mail-user=Mirali.V.Purohit@jpl.nasa.gov         # send-to address


cd /scratch-edge/large-mars-model/SURP_code/LMM


##### ----------------------------------------------------- Pre-training --------------------------------------------------------------------

#### -------- ResNet34 -----------

# python main_pretrain.py --if_training --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --which_instrument "HiRISE" --train_model resnet34 --output_dir /scratch-edge/large-mars-model/models/task_arithmetic --imagenet_pretrain --wandb_enabled
# python main_pretrain.py --if_training --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --which_instrument "CTX" --train_model resnet34 --output_dir /scratch-edge/large-mars-model/models/task_arithmetic --imagenet_pretrain --wandb_enabled
# python main_pretrain.py --if_training --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --which_instrument "THEMIS" --train_model resnet34 --output_dir /scratch-edge/large-mars-model/models/task_arithmetic --imagenet_pretrain --wandb_enabled

# python main_pretrain.py --if_training --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --which_instrument "HiRISE, CTX" --train_model resnet34 --output_dir /scratch-edge/large-mars-model/models/task_arithmetic --imagenet_pretrain --wandb_enabled
# python main_pretrain.py --if_training --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --which_instrument "HiRISE, THEMIS" --train_model resnet34 --output_dir /scratch-edge/large-mars-model/models/task_arithmetic --imagenet_pretrain --wandb_enabled
# python main_pretrain.py --if_training --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --which_instrument "THEMIS, CTX" --train_model resnet34 --output_dir /scratch-edge/large-mars-model/models/task_arithmetic --imagenet_pretrain --wandb_enabled

# python main_pretrain.py --if_training --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --which_instrument "HiRISE, CTX, THEMIS" --train_model resnet34 --output_dir /scratch-edge/large-mars-model/models/task_arithmetic --imagenet_pretrain --wandb_enabled

#### -------- SqueezeNet 1.1 -----

# python main_pretrain.py --if_training --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --which_instrument "HiRISE" --train_model squeezenet1-1 --output_dir /scratch-edge/large-mars-model/models/task_arithmetic --imagenet_pretrain --wandb_enabled
# python main_pretrain.py --if_training --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --which_instrument "CTX" --train_model squeezenet1-1 --output_dir /scratch-edge/large-mars-model/models/task_arithmetic --imagenet_pretrain --wandb_enabled
# python main_pretrain.py --if_training --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --which_instrument "THEMIS" --train_model squeezenet1-1 --output_dir /scratch-edge/large-mars-model/models/task_arithmetic --imagenet_pretrain --wandb_enabled

# python main_pretrain.py --if_training --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --which_instrument "HiRISE, CTX" --train_model squeezenet1-1 --output_dir /scratch-edge/large-mars-model/models/task_arithmetic --imagenet_pretrain --wandb_enabled
# python main_pretrain.py --if_training --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --which_instrument "HiRISE, THEMIS" --train_model squeezenet1-1 --output_dir /scratch-edge/large-mars-model/models/task_arithmetic --imagenet_pretrain --wandb_enabled
# python main_pretrain.py --if_training --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --which_instrument "THEMIS, CTX" --train_model squeezenet1-1 --output_dir /scratch-edge/large-mars-model/models/task_arithmetic --imagenet_pretrain --wandb_enabled

# python main_pretrain.py --if_training --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --which_instrument "HiRISE, CTX, THEMIS" --train_model squeezenet1-1 --output_dir /scratch-edge/large-mars-model/models/task_arithmetic --imagenet_pretrain --wandb_enabled

#### -------- EfficientNet -----

# python main_pretrain.py --if_training --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --which_instrument "HiRISE" --train_model efficientnet-v2-m --output_dir /scratch-edge/large-mars-model/models/task_arithmetic --imagenet_pretrain --wandb_enabled
# python main_pretrain.py --if_training --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --which_instrument "CTX" --train_model efficientnet-v2-m --output_dir /scratch-edge/large-mars-model/models/task_arithmetic --imagenet_pretrain --wandb_enabled
# python main_pretrain.py --if_training --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --which_instrument "THEMIS" --train_model efficientnet-v2-m --output_dir /scratch-edge/large-mars-model/models/task_arithmetic --imagenet_pretrain --wandb_enabled

# python main_pretrain.py --if_training --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --which_instrument "HiRISE, CTX" --train_model efficientnet-v2-m --output_dir /scratch-edge/large-mars-model/models/task_arithmetic --imagenet_pretrain --wandb_enabled
# python main_pretrain.py --if_training --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --which_instrument "HiRISE, THEMIS" --train_model efficientnet-v2-m --output_dir /scratch-edge/large-mars-model/models/task_arithmetic --imagenet_pretrain --wandb_enabled
# python main_pretrain.py --if_training --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --which_instrument "THEMIS, CTX" --train_model efficientnet-v2-m --output_dir /scratch-edge/large-mars-model/models/task_arithmetic --imagenet_pretrain --wandb_enabled

# python main_pretrain.py --if_training --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --which_instrument "HiRISE, CTX, THEMIS" --train_model efficientnet-v2-m --output_dir /scratch-edge/large-mars-model/models/task_arithmetic --imagenet_pretrain --wandb_enabled

#### -------- ViTB_16 -----

# python main_pretrain.py --if_training --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --which_instrument "HiRISE" --train_model vit-b-16 --output_dir /scratch-edge/large-mars-model/models/task_arithmetic --imagenet_pretrain --wandb_enabled
# python main_pretrain.py --if_training --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --which_instrument "CTX" --train_model vit-b-16 --output_dir /scratch-edge/large-mars-model/models/task_arithmetic --imagenet_pretrain --wandb_enabled
# python main_pretrain.py --if_training --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --which_instrument "THEMIS" --train_model vit-b-16 --output_dir /scratch-edge/large-mars-model/models/task_arithmetic --imagenet_pretrain --wandb_enabled

# python main_pretrain.py --if_training --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --which_instrument "HiRISE, CTX" --train_model vit-b-16 --output_dir /scratch-edge/large-mars-model/models/task_arithmetic --imagenet_pretrain --wandb_enabled
# python main_pretrain.py --if_training --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --which_instrument "HiRISE, THEMIS" --train_model vit-b-16 --output_dir /scratch-edge/large-mars-model/models/task_arithmetic --imagenet_pretrain --wandb_enabled
# python main_pretrain.py --if_training --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --which_instrument "THEMIS, CTX" --train_model vit-b-16 --output_dir /scratch-edge/large-mars-model/models/task_arithmetic --imagenet_pretrain --wandb_enabled

# python main_pretrain.py --if_training --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --which_instrument "HiRISE, CTX, THEMIS" --train_model vit-b-16 --output_dir /scratch-edge/large-mars-model/models/task_arithmetic --imagenet_pretrain --wandb_enabled

#### -------- ViTL_16 -----

python main_pretrain.py --if_training --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --which_instrument "HiRISE" --train_model vit-l-16 --output_dir /scratch-edge/large-mars-model/models/task_arithmetic --imagenet_pretrain --wandb_enabled --batch_size 128
python main_pretrain.py --if_training --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --which_instrument "CTX" --train_model vit-l-16 --output_dir /scratch-edge/large-mars-model/models/task_arithmetic --imagenet_pretrain --wandb_enabled --batch_size 128
python main_pretrain.py --if_training --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --which_instrument "THEMIS" --train_model vit-l-16 --output_dir /scratch-edge/large-mars-model/models/task_arithmetic --imagenet_pretrain --wandb_enabled --batch_size 128

python main_pretrain.py --if_training --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --which_instrument "HiRISE, CTX" --train_model vit-l-16 --output_dir /scratch-edge/large-mars-model/models/task_arithmetic --imagenet_pretrain --wandb_enabled --batch_size 128
python main_pretrain.py --if_training --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --which_instrument "HiRISE, THEMIS" --train_model vit-l-16 --output_dir /scratch-edge/large-mars-model/models/task_arithmetic --imagenet_pretrain --wandb_enabled --batch_size 128
python main_pretrain.py --if_training --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --which_instrument "THEMIS, CTX" --train_model vit-l-16 --output_dir /scratch-edge/large-mars-model/models/task_arithmetic --imagenet_pretrain --wandb_enabled --batch_size 128

python main_pretrain.py --if_training --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --which_instrument "HiRISE, CTX, THEMIS" --train_model vit-l-16 --output_dir /scratch-edge/large-mars-model/models/task_arithmetic --imagenet_pretrain --wandb_enabled --batch_size 128


##### ----------------------------------------------------- Validation ------------------------------------------------------------------------

#### -------- ResNet34 -----------

## ''' Last epoch '''
# python main_pretrain.py --if_validation --model_paths hirise_resnet34:500,ctx_resnet34:500 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_resnet34.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data HiRISE --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_ctx_resnet34:500
# python main_pretrain.py --if_validation --model_paths hirise_resnet34:500,themis_resnet34:500 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_resnet34.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data HiRISE --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_themis_resnet34:500
# python main_pretrain.py --if_validation --model_paths ctx_resnet34:500,themis_resnet34:500 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_resnet34.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data HiRISE --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path themis_ctx_resnet34:500
# python main_pretrain.py --if_validation --model_paths hirise_resnet34:500,ctx_resnet34:500,themis_resnet34:500 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_resnet34.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data HiRISE --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_ctx_themis_resnet34:500

# python main_pretrain.py --if_validation --model_paths hirise_resnet34:500,ctx_resnet34:500 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_resnet34.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data CTX --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_ctx_resnet34:500
# python main_pretrain.py --if_validation --model_paths hirise_resnet34:500,themis_resnet34:500 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_resnet34.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data CTX --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_ctx_resnet34:500
# python main_pretrain.py --if_validation --model_paths ctx_resnet34:500,themis_resnet34:500 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_resnet34.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data CTX --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_ctx_resnet34:500
# python main_pretrain.py --if_validation --model_paths hirise_resnet34:500,ctx_resnet34:500,themis_resnet34:500 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_resnet34.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data CTX --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_ctx_resnet34:500

# python main_pretrain.py --if_validation --model_paths hirise_resnet34:500,ctx_resnet34:500 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_resnet34.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data THEMIS --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_ctx_resnet34:500
# python main_pretrain.py --if_validation --model_paths hirise_resnet34:500,themis_resnet34:500 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_resnet34.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data THEMIS --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_ctx_resnet34:500
# python main_pretrain.py --if_validation --model_paths ctx_resnet34:500,themis_resnet34:500 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_resnet34.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data THEMIS --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_ctx_resnet34:500
# python main_pretrain.py --if_validation --model_paths hirise_resnet34:500,ctx_resnet34:500,themis_resnet34:500 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_resnet34.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data THEMIS --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_ctx_resnet34:500

## ''' Equal val loss epoch '''
# python main_pretrain.py --if_validation --model_paths hirise_resnet34:11,ctx_resnet34:500 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_resnet34.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data HiRISE --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_ctx_resnet34:500
# python main_pretrain.py --if_validation --model_paths hirise_resnet34:11,themis_resnet34:17 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_resnet34.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data HiRISE --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_themis_resnet34:500
# python main_pretrain.py --if_validation --model_paths ctx_resnet34:500,themis_resnet34:17 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_resnet34.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data HiRISE --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path themis_ctx_resnet34:500
# python main_pretrain.py --if_validation --model_paths hirise_resnet34:11,ctx_resnet34:500,themis_resnet34:17 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_resnet34.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data HiRISE --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_ctx_themis_resnet34:500

# python main_pretrain.py --if_validation --model_paths hirise_resnet34:11,ctx_resnet34:500 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_resnet34.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data CTX --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_ctx_resnet34:500
# python main_pretrain.py --if_validation --model_paths hirise_resnet34:11,themis_resnet34:17 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_resnet34.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data CTX --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_themis_resnet34:500
# python main_pretrain.py --if_validation --model_paths ctx_resnet34:500,themis_resnet34:17 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_resnet34.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data CTX --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path themis_ctx_resnet34:500
# python main_pretrain.py --if_validation --model_paths hirise_resnet34:11,ctx_resnet34:500,themis_resnet34:17 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_resnet34.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data CTX --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_ctx_themis_resnet34:500

# python main_pretrain.py --if_validation --model_paths hirise_resnet34:11,ctx_resnet34:500 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_resnet34.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data THEMIS --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_ctx_resnet34:500
# python main_pretrain.py --if_validation --model_paths hirise_resnet34:11,themis_resnet34:17 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_resnet34.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data THEMIS --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_themis_resnet34:500
# python main_pretrain.py --if_validation --model_paths ctx_resnet34:500,themis_resnet34:17 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_resnet34.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data THEMIS --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path themis_ctx_resnet34:500
# python main_pretrain.py --if_validation --model_paths hirise_resnet34:11,ctx_resnet34:500,themis_resnet34:17 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_resnet34.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data THEMIS --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_ctx_themis_resnet34:500

## ''' Early stopping epoch '''
# python main_pretrain.py --if_validation --model_paths hirise_resnet34:151,ctx_resnet34:289 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_resnet34.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data HiRISE --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_ctx_resnet34:500
# python main_pretrain.py --if_validation --model_paths hirise_resnet34:151,themis_resnet34:193 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_resnet34.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data HiRISE --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_themis_resnet34:500
# python main_pretrain.py --if_validation --model_paths ctx_resnet34:289,themis_resnet34:193 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_resnet34.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data HiRISE --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path themis_ctx_resnet34:500
# python main_pretrain.py --if_validation --model_paths hirise_resnet34:151,ctx_resnet34:289,themis_resnet34:193 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_resnet34.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data HiRISE --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_ctx_themis_resnet34:500

# python main_pretrain.py --if_validation --model_paths hirise_resnet34:151,ctx_resnet34:289 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_resnet34.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data CTX --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_ctx_resnet34:500
# python main_pretrain.py --if_validation --model_paths hirise_resnet34:151,themis_resnet34:193 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_resnet34.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data CTX --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_themis_resnet34:500
# python main_pretrain.py --if_validation --model_paths ctx_resnet34:289,themis_resnet34:193 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_resnet34.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data CTX --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path themis_ctx_resnet34:500
# python main_pretrain.py --if_validation --model_paths hirise_resnet34:151,ctx_resnet34:289,themis_resnet34:193 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_resnet34.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data CTX --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_ctx_themis_resnet34:500

# python main_pretrain.py --if_validation --model_paths hirise_resnet34:151,ctx_resnet34:289 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_resnet34.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data THEMIS --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_ctx_resnet34:500
# python main_pretrain.py --if_validation --model_paths hirise_resnet34:151,themis_resnet34:193 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_resnet34.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data THEMIS --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_themis_resnet34:500
# python main_pretrain.py --if_validation --model_paths ctx_resnet34:289,themis_resnet34:193 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_resnet34.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data THEMIS --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path themis_ctx_resnet34:500
# python main_pretrain.py --if_validation --model_paths hirise_resnet34:151,ctx_resnet34:289,themis_resnet34:193 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_resnet34.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data THEMIS --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_ctx_themis_resnet34:500


#### -------- EfficientNet -----

## ''' Last epoch '''
# python main_pretrain.py --if_validation --model_paths hirise_efficientnet-v2-m:500,ctx_efficientnet-v2-m:500 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_efficientnet-v2-m.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data HiRISE --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_ctx_efficientnet-v2-m:500
# python main_pretrain.py --if_validation --model_paths hirise_efficientnet-v2-m:500,themis_efficientnet-v2-m:500 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_efficientnet-v2-m.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data HiRISE --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_ctx_efficientnet-v2-m:500
# python main_pretrain.py --if_validation --model_paths ctx_efficientnet-v2-m:500,themis_efficientnet-v2-m:500 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_efficientnet-v2-m.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data HiRISE --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_ctx_efficientnet-v2-m:500
# python main_pretrain.py --if_validation --model_paths hirise_efficientnet-v2-m:500,ctx_efficientnet-v2-m:500,themis_efficientnet-v2-m:500 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_efficientnet-v2-m.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data HiRISE --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_ctx_efficientnet-v2-m:500

# python main_pretrain.py --if_validation --model_paths hirise_efficientnet-v2-m:500,ctx_efficientnet-v2-m:500 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_efficientnet-v2-m.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data CTX --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_ctx_efficientnet-v2-m:500
# python main_pretrain.py --if_validation --model_paths hirise_efficientnet-v2-m:500,themis_efficientnet-v2-m:500 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_efficientnet-v2-m.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data CTX --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_ctx_efficientnet-v2-m:500
# python main_pretrain.py --if_validation --model_paths ctx_efficientnet-v2-m:500,themis_efficientnet-v2-m:500 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_efficientnet-v2-m.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data CTX --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_ctx_efficientnet-v2-m:500
# python main_pretrain.py --if_validation --model_paths hirise_efficientnet-v2-m:500,ctx_efficientnet-v2-m:500,themis_efficientnet-v2-m:500 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_efficientnet-v2-m.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data CTX --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_ctx_efficientnet-v2-m:500

# python main_pretrain.py --if_validation --model_paths hirise_efficientnet-v2-m:500,ctx_efficientnet-v2-m:500 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_efficientnet-v2-m.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data THEMIS --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_ctx_efficientnet-v2-m:500
# python main_pretrain.py --if_validation --model_paths hirise_efficientnet-v2-m:500,themis_efficientnet-v2-m:500 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_efficientnet-v2-m.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data THEMIS --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_ctx_efficientnet-v2-m:500
# python main_pretrain.py --if_validation --model_paths ctx_efficientnet-v2-m:500,themis_efficientnet-v2-m:500 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_efficientnet-v2-m.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data THEMIS --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_ctx_efficientnet-v2-m:500
# python main_pretrain.py --if_validation --model_paths hirise_efficientnet-v2-m:500,ctx_efficientnet-v2-m:500,themis_efficientnet-v2-m:500 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_efficientnet-v2-m.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data THEMIS --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_ctx_efficientnet-v2-m:500

## '''  Equal val loss epoch  '''
# python main_pretrain.py --if_validation --model_paths hirise_efficientnet-v2-m:6,ctx_efficientnet-v2-m:500 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_efficientnet-v2-m.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data HiRISE --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_ctx_efficientnet-v2-m:500
# python main_pretrain.py --if_validation --model_paths hirise_efficientnet-v2-m:6,themis_efficientnet-v2-m:29 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_efficientnet-v2-m.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data HiRISE --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_ctx_efficientnet-v2-m:500
# python main_pretrain.py --if_validation --model_paths ctx_efficientnet-v2-m:500,themis_efficientnet-v2-m:29 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_efficientnet-v2-m.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data HiRISE --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_ctx_efficientnet-v2-m:500
# python main_pretrain.py --if_validation --model_paths hirise_efficientnet-v2-m:6,ctx_efficientnet-v2-m:500,themis_efficientnet-v2-m:29 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_efficientnet-v2-m.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data HiRISE --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_ctx_efficientnet-v2-m:500

# python main_pretrain.py --if_validation --model_paths hirise_efficientnet-v2-m:6,ctx_efficientnet-v2-m:500 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_efficientnet-v2-m.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data CTX --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_ctx_efficientnet-v2-m:500
# python main_pretrain.py --if_validation --model_paths hirise_efficientnet-v2-m:6,themis_efficientnet-v2-m:29 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_efficientnet-v2-m.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data CTX --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_ctx_efficientnet-v2-m:500
# python main_pretrain.py --if_validation --model_paths ctx_efficientnet-v2-m:500,themis_efficientnet-v2-m:29 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_efficientnet-v2-m.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data CTX --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_ctx_efficientnet-v2-m:500
# python main_pretrain.py --if_validation --model_paths hirise_efficientnet-v2-m:6,ctx_efficientnet-v2-m:500,themis_efficientnet-v2-m:29 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_efficientnet-v2-m.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data CTX --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_ctx_efficientnet-v2-m:500

# python main_pretrain.py --if_validation --model_paths hirise_efficientnet-v2-m:6,ctx_efficientnet-v2-m:500 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_efficientnet-v2-m.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data THEMIS --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_ctx_efficientnet-v2-m:500
# python main_pretrain.py --if_validation --model_paths hirise_efficientnet-v2-m:6,themis_efficientnet-v2-m:29 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_efficientnet-v2-m.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data THEMIS --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_ctx_efficientnet-v2-m:500
# python main_pretrain.py --if_validation --model_paths ctx_efficientnet-v2-m:500,themis_efficientnet-v2-m:29 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_efficientnet-v2-m.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data THEMIS --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_ctx_efficientnet-v2-m:500
# python main_pretrain.py --if_validation --model_paths hirise_efficientnet-v2-m:6,ctx_efficientnet-v2-m:500,themis_efficientnet-v2-m:29 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_efficientnet-v2-m.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data THEMIS --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_ctx_efficientnet-v2-m:500

## ''' Early stopping epoch '''
# python main_pretrain.py --if_validation --model_paths hirise_efficientnet-v2-m:126,ctx_efficientnet-v2-m:463 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_efficientnet-v2-m.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data HiRISE --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_ctx_efficientnet-v2-m:500
# python main_pretrain.py --if_validation --model_paths hirise_efficientnet-v2-m:126,themis_efficientnet-v2-m:285 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_efficientnet-v2-m.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data HiRISE --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_ctx_efficientnet-v2-m:500
# python main_pretrain.py --if_validation --model_paths ctx_efficientnet-v2-m:463,themis_efficientnet-v2-m:285 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_efficientnet-v2-m.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data HiRISE --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_ctx_efficientnet-v2-m:500
# python main_pretrain.py --if_validation --model_paths hirise_efficientnet-v2-m:126,ctx_efficientnet-v2-m:463,themis_efficientnet-v2-m:285 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_efficientnet-v2-m.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data HiRISE --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_ctx_efficientnet-v2-m:500

# python main_pretrain.py --if_validation --model_paths hirise_efficientnet-v2-m:126,ctx_efficientnet-v2-m:463 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_efficientnet-v2-m.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data CTX --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_ctx_efficientnet-v2-m:500
# python main_pretrain.py --if_validation --model_paths hirise_efficientnet-v2-m:126,themis_efficientnet-v2-m:285 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_efficientnet-v2-m.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data CTX --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_ctx_efficientnet-v2-m:500
# python main_pretrain.py --if_validation --model_paths ctx_efficientnet-v2-m:463,themis_efficientnet-v2-m:285 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_efficientnet-v2-m.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data CTX --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_ctx_efficientnet-v2-m:500
# python main_pretrain.py --if_validation --model_paths hirise_efficientnet-v2-m:126,ctx_efficientnet-v2-m:463,themis_efficientnet-v2-m:285 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_efficientnet-v2-m.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data CTX --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_ctx_efficientnet-v2-m:500

# python main_pretrain.py --if_validation --model_paths hirise_efficientnet-v2-m:126,ctx_efficientnet-v2-m:463 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_efficientnet-v2-m.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data THEMIS --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_ctx_efficientnet-v2-m:500
# python main_pretrain.py --if_validation --model_paths hirise_efficientnet-v2-m:126,themis_efficientnet-v2-m:285 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_efficientnet-v2-m.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data THEMIS --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_ctx_efficientnet-v2-m:500
# python main_pretrain.py --if_validation --model_paths ctx_efficientnet-v2-m:463,themis_efficientnet-v2-m:285 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_efficientnet-v2-m.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data THEMIS --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_ctx_efficientnet-v2-m:500
# python main_pretrain.py --if_validation --model_paths hirise_efficientnet-v2-m:126,ctx_efficientnet-v2-m:463,themis_efficientnet-v2-m:285 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_efficientnet-v2-m.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data THEMIS --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_ctx_efficientnet-v2-m:500


#### -------- ViTB_16 -----

## ''' Last epoch '''
# python main_pretrain.py --if_validation --model_paths hirise_vit-b-16:500,ctx_vit-b-16:500 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_vit-b-16.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data HiRISE --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_ctx_vit-b-16:500
# python main_pretrain.py --if_validation --model_paths hirise_vit-b-16:500,themis_vit-b-16:500 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_vit-b-16.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data HiRISE --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_ctx_vit-b-16:500
# python main_pretrain.py --if_validation --model_paths ctx_vit-b-16:500,themis_vit-b-16:500 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_vit-b-16.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data HiRISE --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_ctx_vit-b-16:500
# python main_pretrain.py --if_validation --model_paths hirise_vit-b-16:500,ctx_vit-b-16:500,themis_vit-b-16:500 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_vit-b-16.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data HiRISE --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_ctx_vit-b-16:500

# python main_pretrain.py --if_validation --model_paths hirise_vit-b-16:500,ctx_vit-b-16:500 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_vit-b-16.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data CTX --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_ctx_vit-b-16:500
# python main_pretrain.py --if_validation --model_paths hirise_vit-b-16:500,themis_vit-b-16:500 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_vit-b-16.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data CTX --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_ctx_vit-b-16:500
# python main_pretrain.py --if_validation --model_paths ctx_vit-b-16:500,themis_vit-b-16:500 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_vit-b-16.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data CTX --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_ctx_vit-b-16:500
# python main_pretrain.py --if_validation --model_paths hirise_vit-b-16:500,ctx_vit-b-16:500,themis_vit-b-16:500 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_vit-b-16.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data CTX --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_ctx_vit-b-16:500

# python main_pretrain.py --if_validation --model_paths hirise_vit-b-16:500,ctx_vit-b-16:500 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_vit-b-16.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data THEMIS --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_ctx_vit-b-16:500
# python main_pretrain.py --if_validation --model_paths hirise_vit-b-16:500,themis_vit-b-16:500 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_vit-b-16.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data THEMIS --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_ctx_vit-b-16:500
# python main_pretrain.py --if_validation --model_paths ctx_vit-b-16:500,themis_vit-b-16:500 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_vit-b-16.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data THEMIS --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_ctx_vit-b-16:500
# python main_pretrain.py --if_validation --model_paths hirise_vit-b-16:500,ctx_vit-b-16:500,themis_vit-b-16:500 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_vit-b-16.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data THEMIS --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_ctx_vit-b-16:500

## '''  Equal val loss epoch  '''
# python main_pretrain.py --if_validation --model_paths hirise_vit-b-16:9,ctx_vit-b-16:500 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_vit-b-16.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data HiRISE --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_ctx_vit-b-16:500
# python main_pretrain.py --if_validation --model_paths hirise_vit-b-16:9,themis_vit-b-16:171 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_vit-b-16.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data HiRISE --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_ctx_vit-b-16:500
# python main_pretrain.py --if_validation --model_paths ctx_vit-b-16:500,themis_vit-b-16:171 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_vit-b-16.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data HiRISE --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_ctx_vit-b-16:500
# python main_pretrain.py --if_validation --model_paths hirise_vit-b-16:9,ctx_vit-b-16:500,themis_vit-b-16:171 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_vit-b-16.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data HiRISE --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_ctx_vit-b-16:500

# python main_pretrain.py --if_validation --model_paths hirise_vit-b-16:9ctx_vit-b-16:500 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_vit-b-16.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data CTX --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_ctx_vit-b-16:500
# python main_pretrain.py --if_validation --model_paths hirise_vit-b-16:9,themis_vit-b-16:171 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_vit-b-16.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data CTX --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_ctx_vit-b-16:500
# python main_pretrain.py --if_validation --model_paths ctx_vit-b-16:500,themis_vit-b-16:171 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_vit-b-16.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data CTX --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_ctx_vit-b-16:500
# python main_pretrain.py --if_validation --model_paths hirise_vit-b-16:9,ctx_vit-b-16:500,themis_vit-b-16:171 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_vit-b-16.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data CTX --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_ctx_vit-b-16:500

# python main_pretrain.py --if_validation --model_paths hirise_vit-b-16:9,ctx_vit-b-16:500 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_vit-b-16.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data THEMIS --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_ctx_vit-b-16:500
# python main_pretrain.py --if_validation --model_paths hirise_vit-b-16:9,themis_vit-b-16:171 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_vit-b-16.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data THEMIS --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_ctx_vit-b-16:500
# python main_pretrain.py --if_validation --model_paths ctx_vit-b-16:500,themis_vit-b-16:171 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_vit-b-16.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data THEMIS --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_ctx_vit-b-16:500
# python main_pretrain.py --if_validation --model_paths hirise_vit-b-16:9,ctx_vit-b-16:500,themis_vit-b-16:171 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_vit-b-16.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data THEMIS --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_ctx_vit-b-16:500

## ''' Early stopping epoch '''
# python main_pretrain.py --if_validation --model_paths hirise_vit-b-16:77,ctx_vit-b-16:160 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_vit-b-16.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data HiRISE --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_ctx_vit-b-16:500
# python main_pretrain.py --if_validation --model_paths hirise_vit-b-16:77,themis_vit-b-16:46 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_vit-b-16.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data HiRISE --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_ctx_vit-b-16:500
# python main_pretrain.py --if_validation --model_paths ctx_vit-b-16:160,themis_vit-b-16:46 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_vit-b-16.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data HiRISE --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_ctx_vit-b-16:500
# python main_pretrain.py --if_validation --model_paths hirise_vit-b-16:77,ctx_vit-b-16:160,themis_vit-b-16:46 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_vit-b-16.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data HiRISE --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_ctx_vit-b-16:500

# python main_pretrain.py --if_validation --model_paths hirise_vit-b-16:77,ctx_vit-b-16:160 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_vit-b-16.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data CTX --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_ctx_vit-b-16:500
# python main_pretrain.py --if_validation --model_paths hirise_vit-b-16:77,themis_vit-b-16:46 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_vit-b-16.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data CTX --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_ctx_vit-b-16:500
# python main_pretrain.py --if_validation --model_paths ctx_vit-b-16:160,themis_vit-b-16:46 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_vit-b-16.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data CTX --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_ctx_vit-b-16:500
# python main_pretrain.py --if_validation --model_paths hirise_vit-b-16:77,ctx_vit-b-16:160,themis_vit-b-16:46 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_vit-b-16.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data CTX --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_ctx_vit-b-16:500

# python main_pretrain.py --if_validation --model_paths hirise_vit-b-16:77,ctx_vit-b-16:160 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_vit-b-16.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data THEMIS --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_ctx_vit-b-16:500
# python main_pretrain.py --if_validation --model_paths hirise_vit-b-16:77,themis_vit-b-16:46 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_vit-b-16.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data THEMIS --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_ctx_vit-b-16:500
# python main_pretrain.py --if_validation --model_paths ctx_vit-b-16:160,themis_vit-b-16:46 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_vit-b-16.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data THEMIS --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_ctx_vit-b-16:500
# python main_pretrain.py --if_validation --model_paths hirise_vit-b-16:77,ctx_vit-b-16:160,themis_vit-b-16:46 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_vit-b-16.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data THEMIS --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_ctx_vit-b-16:500


#### -------- SqueezeNet 1.1 -----

# python main_pretrain.py --if_validation --model_paths hirise_squeezenet1-1:500,ctx_squeezenet1-1:500 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_squeezenet1-1.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data HiRISE --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_ctx_squeezenet1-1:500
# python main_pretrain.py --if_validation --model_paths hirise_squeezenet1-1:500,themis_squeezenet1-1:500 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_squeezenet1-1.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data HiRISE --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_ctx_squeezenet1-1:500
# python main_pretrain.py --if_validation --model_paths ctx_squeezenet1-1:500,themis_squeezenet1-1:500 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_squeezenet1-1.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data HiRISE --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_ctx_squeezenet1-1:500
# python main_pretrain.py --if_validation --model_paths hirise_squeezenet1-1:500,ctx_squeezenet1-1:500,themis_squeezenet1-1:500 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_squeezenet1-1.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data HiRISE --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_ctx_squeezenet1-1:500

# python main_pretrain.py --if_validation --model_paths hirise_squeezenet1-1:500,ctx_squeezenet1-1:500 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_squeezenet1-1.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data CTX --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_ctx_squeezenet1-1:500
# python main_pretrain.py --if_validation --model_paths hirise_squeezenet1-1:500,themis_squeezenet1-1:500 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_squeezenet1-1.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data CTX --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_ctx_squeezenet1-1:500
# python main_pretrain.py --if_validation --model_paths ctx_squeezenet1-1:500,themis_squeezenet1-1:500 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_squeezenet1-1.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data CTX --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_ctx_squeezenet1-1:500
# python main_pretrain.py --if_validation --model_paths hirise_squeezenet1-1:500,ctx_squeezenet1-1:500,themis_squeezenet1-1:500 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_squeezenet1-1.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data CTX --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_ctx_squeezenet1-1:500

# python main_pretrain.py --if_validation --model_paths hirise_squeezenet1-1:500,ctx_squeezenet1-1:500 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_squeezenet1-1.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data THEMIS --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_ctx_squeezenet1-1:500
# python main_pretrain.py --if_validation --model_paths hirise_squeezenet1-1:500,themis_squeezenet1-1:500 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_squeezenet1-1.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data THEMIS --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_ctx_squeezenet1-1:500
# python main_pretrain.py --if_validation --model_paths ctx_squeezenet1-1:500,themis_squeezenet1-1:500 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_squeezenet1-1.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data THEMIS --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_ctx_squeezenet1-1:500
# python main_pretrain.py --if_validation --model_paths hirise_squeezenet1-1:500,ctx_squeezenet1-1:500,themis_squeezenet1-1:500 --pretrained_model_path "/scratch-edge/large-mars-model/models/task_arithmetic/imagenet/pre_trained_squeezenet1-1.pth" --output_dir "/scratch-edge/large-mars-model/models/task_arithmetic" --val_data THEMIS --data_dir /scratch-edge/large-mars-model/pretraining_data/task_arithmetic --jointly_trained_model_path hirise_ctx_squeezenet1-1:500
